import type { OrderAlert } from '../common/OrderAlertBanner'

export const DASHBOARD_ALERTS: OrderAlert[] = [
  {
    id: 'dash-security-1',
    type: 'suspicious-login',
    title: '安全提醒：检测到异常登录',
    message: '您的账号于 2026-06-25 03:42 从异常 IP 地址（美国 · 迈阿密）登录。如非本人操作，请立即修改密码并检查账号安全设置。',
    refId: 'IP: 192.168.x.x',
    severity: 'high',
    actionLabel: '检查登录记录',
    actionPath: '/messages',
    secondaryActionLabel: '修改密码',
    secondaryActionPath: '/messages',
  },
  {
    id: 'dash-1',
    type: 'order-overdue',
    title: '紧急：订单履约受影响',
    message: '120 个订单在分拣环节卡滞超过 4 小时，35 个订单 SLA 即将到期。请及时关注处理进度，避免影响客户体验评分。',
    refId: '155 orders at risk',
    severity: 'high',
    actionLabel: '查看详情',
    actionPath: '/support/item/WI-011',
    secondaryActionLabel: '申请加急',
    secondaryActionPath: '/support/requests/new?topic=expedite&priority=Critical',
  },
  {
    id: 'dash-2',
    type: 'low-stock',
    title: '库存健康提醒',
    message: 'TCORE-CABLE 库存低于安全阈值，FW-2024-RED 300 件冻结中。部分订单可能因库存不足无法按时发货。',
    refId: '2 SKUs affected',
    severity: 'high',
    actionLabel: '查看库存状态',
    actionPath: '/inventory/activity',
    secondaryActionLabel: '安排补货',
    secondaryActionPath: '/support/requests/new',
  },
  {
    id: 'dash-3',
    type: 'sla-risk',
    title: '本周 OTIF 预警',
    message: '本周 OTIF 达标率预计下降至 85%，主要受承运商延误和库存不足影响。建议提前采取措施保障服务水平。',
    refId: 'OTIF Risk',
    severity: 'medium',
    actionLabel: '查看改善建议',
    actionPath: '/support/item/WI-015',
  },
]
